-- PostgreSQL
-- ntrip_accuracy_monitor/persistence/migrations/V001__initial.sql
--
-- Создание базовой схемы хранения сеансов и эпох ровера.
-- Эпохи — основная таблица результатов 1 Гц с трёх приёмников.

-- ----------------------------------------------------------------------------
-- Таблица сеансов наблюдений.
-- ----------------------------------------------------------------------------

CREATE TABLE sessions (
    session_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at           TIMESTAMPTZ,
    description        TEXT NOT NULL,
    reference_antenna  JSONB,
    config_snapshot    JSONB,
    CONSTRAINT sessions_time_order
        CHECK (ended_at IS NULL OR ended_at >= started_at)
);

COMMENT ON TABLE  sessions IS
    'Лабораторные сеансы наблюдений: один сеанс — один прогон 24 ч.';
COMMENT ON COLUMN sessions.reference_antenna IS
    'Снимок ReferenceAntennaConfig на момент старта сеанса (lat/lon/h/source).';
COMMENT ON COLUMN sessions.config_snapshot IS
    'Полный снимок конфигурации приложения для воспроизводимости результатов.';

-- ----------------------------------------------------------------------------
-- Таблица эпох ровера. Основная таблица результатов.
--
-- Имя поля канала — stream_id, единое с доменной моделью Epoch.
-- gga_quality в БД не дублируется: значение SolutionMode и есть GGA quality
-- (IntEnum со значениями 0..8 из NMEA-0183).
-- 1σ ошибки — в ENU (east/north/up), как они приходят из NMEA GST после
-- приведения в локальную систему.
-- ----------------------------------------------------------------------------

CREATE TABLE epochs (
    epoch_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id            BIGINT      NOT NULL
                          REFERENCES sessions(session_id) ON DELETE CASCADE,
    stream_id             VARCHAR(64) NOT NULL,
    epoch_time            TIMESTAMPTZ NOT NULL,

    -- Координаты из NMEA GGA, в WGS-84.
    latitude_deg          DOUBLE PRECISION NOT NULL,
    longitude_deg         DOUBLE PRECISION NOT NULL,
    ellipsoidal_height_m  DOUBLE PRECISION NOT NULL,

    -- Качество решения.
    solution_mode         SMALLINT NOT NULL,
    age_of_corrections_s  REAL,
    satellites_used       SMALLINT,
    hdop                  REAL,
    pdop                  REAL,

    -- 1σ оценки из NMEA GST в локальной ENU (могут отсутствовать).
    sigma_east_m          REAL,
    sigma_north_m         REAL,
    sigma_up_m            REAL,

    CONSTRAINT epochs_lat_range
        CHECK (latitude_deg  BETWEEN -90  AND 90),
    CONSTRAINT epochs_lon_range
        CHECK (longitude_deg BETWEEN -180 AND 180),
    CONSTRAINT epochs_solution_mode_range
        CHECK (solution_mode BETWEEN 0 AND 8),

    CONSTRAINT epochs_unique_per_stream
        UNIQUE (session_id, stream_id, epoch_time)
);

COMMENT ON TABLE  epochs IS
    'Эпохи ровера 1 Гц. Одна строка — одно GGA-сообщение от одного канала.';
COMMENT ON COLUMN epochs.stream_id IS
    'Идентификатор канала: base / rover_rtk / rover_spp.';
COMMENT ON COLUMN epochs.epoch_time IS
    'UTC время эпохи из NMEA GGA, привязано к шкале UTC (не GPS-time).';
COMMENT ON COLUMN epochs.solution_mode IS
    'Доменный код режима решения (IntEnum), значение совпадает с GGA quality 0..8.';
COMMENT ON COLUMN epochs.age_of_corrections_s IS
    'Поле "Age of differential GPS data" из GGA. NULL для эпох без поправок.';
COMMENT ON COLUMN epochs.sigma_east_m IS
    '1σ оценка ошибки по восточной оси в метрах (ENU из NMEA GST).';
COMMENT ON COLUMN epochs.sigma_north_m IS
    '1σ оценка ошибки по северной оси в метрах (ENU из NMEA GST).';
COMMENT ON COLUMN epochs.sigma_up_m IS
    '1σ оценка ошибки по вертикали в метрах (ENU из NMEA GST).';

-- ----------------------------------------------------------------------------
-- Индексы для аналитических запросов.
-- ----------------------------------------------------------------------------

-- BRIN-индекс по epoch_time: данные пишутся монотонно по времени,
-- хорошая корреляция значения и физического порядка на диске.
CREATE INDEX epochs_epoch_time_brin
    ON epochs USING BRIN (epoch_time);

-- Композитный btree для группировок по solution_mode внутри сеанса
-- (метрики по режимам — глава 8 методики).
CREATE INDEX epochs_session_mode_time
    ON epochs (session_id, solution_mode, epoch_time);

-- Уникальный индекс эпохи уже создан UNIQUE-ограничением выше,
-- он же обслуживает запросы фильтра (session_id, stream_id, epoch_time).
