-- PostgreSQL
-- ntrip_accuracy_monitor/persistence/migrations/V002__rtcm.sql
--
-- Аудит RTCM-сообщений, проходящих через наш NTRIP-кастер от базы к роверу.
-- Хранятся только метаданные кадра — сами байты не сохраняем
-- Запись ведётся для всех типов сообщений,
-- которые приходят в потоке от приёмника (RTCM 3.x наблюдения,
-- эфемериды, дескриптор станции).

CREATE TABLE rtcm_messages (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id            BIGINT      NOT NULL
                          REFERENCES sessions(session_id) ON DELETE CASCADE,

    -- Время прихода кадра на нашу сторону (хост мониторинга).
    -- Это не время эпохи RTCM, а момент приёма кадра нашей системой.
    received_at           TIMESTAMPTZ NOT NULL,

    msg_type              SMALLINT    NOT NULL,
    reference_station_id  INTEGER,
    satellite_id          SMALLINT,
    byte_length           SMALLINT    NOT NULL,

    CONSTRAINT rtcm_msg_type_range
        CHECK (msg_type BETWEEN 1001 AND 4095),
    CONSTRAINT rtcm_byte_length_range
        CHECK (byte_length BETWEEN 6 AND 1029)
);

COMMENT ON TABLE  rtcm_messages IS
    'Поминутный аудит метаданных всех RTCM-сообщений от базы. Без сырых байт.';
COMMENT ON COLUMN rtcm_messages.received_at IS
    'Момент чтения кадра нашей системой, не время эпохи RTCM.';
COMMENT ON COLUMN rtcm_messages.msg_type IS
    'Тип сообщения RTCM 3.x (DF002), например 1004/1012/1019/1020/1033.';
COMMENT ON COLUMN rtcm_messages.reference_station_id IS
    'Идентификатор базовой станции из самого сообщения (DF003).';
COMMENT ON COLUMN rtcm_messages.satellite_id IS
    'Идентификатор спутника. NULL для сообщений без спутника (1006, 1033, наблюдения).';
COMMENT ON COLUMN rtcm_messages.byte_length IS
    'Полная длина кадра в байтах: преамбула + длина + payload + CRC-24Q.';

-- ----------------------------------------------------------------------------
-- Индексы.
-- ----------------------------------------------------------------------------

-- BRIN по времени приёма — тот же принцип, что и у epochs.
CREATE INDEX rtcm_messages_received_at_brin
    ON rtcm_messages USING BRIN (received_at);

-- Композитный btree для запросов «все сообщения типа X в сеансе Y за интервал».
CREATE INDEX rtcm_messages_session_type_time
    ON rtcm_messages (session_id, msg_type, received_at);
