-- PostgreSQL
-- ntrip_accuracy_monitor/persistence/migrations/V004__metrics.sql
--
-- GUI читает session_metrics + metrics_by_age, ничего не считает.
--
-- session_metrics — одна строка на (session_id, stream_id, solution_mode_filter),
-- ON CONFLICT DO UPDATE при пересчёте (metrics_id стабилен).
-- metrics_by_age — детализация по возрасту поправок, FK ON DELETE CASCADE.

-- ----------------------------------------------------------------------------
-- Таблица session_metrics: одна строка на режим расчёта.
-- ----------------------------------------------------------------------------

CREATE TABLE session_metrics (
    metrics_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id                  BIGINT      NOT NULL
                                REFERENCES sessions(session_id) ON DELETE CASCADE,
    stream_id                   VARCHAR(64) NOT NULL,
    solution_mode_filter        VARCHAR(24) NOT NULL,

    epochs_total                INTEGER NOT NULL,
    epochs_after_filter         INTEGER NOT NULL,
    epochs_rejected_outliers    INTEGER NOT NULL,

    -- Основные метрики точности
    hrms_m                      DOUBLE PRECISION NOT NULL,
    vrms_m                      DOUBLE PRECISION NOT NULL,
    two_drms_m                  DOUBLE PRECISION NOT NULL,
    cep50_m                     DOUBLE PRECISION NOT NULL,
    r95_m                       DOUBLE PRECISION NOT NULL,
    three_drms_m                DOUBLE PRECISION NOT NULL,

    -- Дополнительно для отчета.
    error_3d_mean_m             DOUBLE PRECISION NOT NULL,
    error_3d_max_m              DOUBLE PRECISION NOT NULL,

    -- RTK-специфика: NULL для не-RTK_FIXED_FLOAT фильтров.
    fixed_ratio                 DOUBLE PRECISION,
    ttff_s                      DOUBLE PRECISION,

    -- Форма распределения
    skewness_radial             DOUBLE PRECISION NOT NULL,

    -- Параметры расчета (audit trail, не AccuracyMetrics).
    -- NULL = выбраковка отключена (compute_metrics(..., outlier_factor=None)).
    outlier_factor              REAL,

    -- Параметры биннинга по возрасту поправок. NULL если для этой строки
    -- метрик не считались age-bins. Нужны для round-trip восстановления
    -- AgeBinMetricsSeries из metrics_by_age.
    age_bin_width_s             REAL,
    age_bin_min_epochs          INTEGER,

    computed_at                 TIMESTAMPTZ NOT NULL,

    CONSTRAINT session_metrics_uniq
        UNIQUE (session_id, stream_id, solution_mode_filter),
    CONSTRAINT session_metrics_filter_check
        CHECK (solution_mode_filter IN
               ('SPP', 'DGNSS', 'RTK_FIXED', 'RTK_FIXED_FLOAT')),
    CONSTRAINT session_metrics_counts_check
        CHECK (epochs_total             >= 0
           AND epochs_after_filter      >= 0
           AND epochs_rejected_outliers >= 0
           AND epochs_after_filter      <= epochs_total
           AND epochs_rejected_outliers <= epochs_after_filter),
    CONSTRAINT session_metrics_fixed_ratio_check
        CHECK (fixed_ratio IS NULL
            OR (fixed_ratio >= 0.0 AND fixed_ratio <= 1.0)),
    CONSTRAINT session_metrics_ttff_check
        CHECK (ttff_s IS NULL OR ttff_s >= 0.0),
    CONSTRAINT session_metrics_outlier_factor_check
        CHECK (outlier_factor IS NULL OR outlier_factor > 0.0),
    CONSTRAINT session_metrics_age_bin_width_check
        CHECK (age_bin_width_s IS NULL OR age_bin_width_s > 0.0),
    CONSTRAINT session_metrics_age_bin_min_epochs_check
        CHECK (age_bin_min_epochs IS NULL OR age_bin_min_epochs >= 0)
);

COMMENT ON TABLE  session_metrics IS
    'Рассчитанные метрики точности по выборке (session, stream, режим). '
    'Перезаписываются ON CONFLICT при пересчёте, metrics_id стабилен.';
COMMENT ON COLUMN session_metrics.solution_mode_filter IS
    'SPP | DGNSS | RTK_FIXED | RTK_FIXED_FLOAT — значения SolutionModeFilter.';
COMMENT ON COLUMN session_metrics.epochs_total IS
    'Все эпохи канала в сеансе (до фильтра по режиму). Интерпретация A';
COMMENT ON COLUMN session_metrics.epochs_after_filter IS
    'После фильтра по solution_mode_filter, до выбраковки выбросов.';
COMMENT ON COLUMN session_metrics.epochs_rejected_outliers IS
    'Выкинуто на втором проходе. 0 если outlier_factor IS NULL.';
COMMENT ON COLUMN session_metrics.outlier_factor IS
    'Порог 2-проходной выбраковки (методика 8.4). NULL = выбраковка отключена.';
COMMENT ON COLUMN session_metrics.age_bin_width_s IS
    'Ширина бина по age_of_corrections_s. NULL если age-bins не считались.';
COMMENT ON COLUMN session_metrics.age_bin_min_epochs IS
    'Порог is_significant для metrics_by_age. NULL если age-bins не считались.';
COMMENT ON COLUMN session_metrics.computed_at IS
    'Момент расчёта (UTC tz-aware), из MetricsService, а не из БД.';

-- UNIQUE-ограничение автоматически создаёт btree по
-- (session_id, stream_id, solution_mode_filter) — отдельный CREATE INDEX не нужен.

-- ----------------------------------------------------------------------------
-- Таблица metrics_by_age: бины по age_of_corrections_s.
-- ----------------------------------------------------------------------------

CREATE TABLE metrics_by_age (
    bin_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metrics_id          BIGINT NOT NULL
                        REFERENCES session_metrics(metrics_id) ON DELETE CASCADE,

    age_bin_start_s     REAL NOT NULL,
    age_bin_end_s       REAL NOT NULL,
    epochs_count        INTEGER NOT NULL,

    hrms_m              DOUBLE PRECISION NOT NULL,
    vrms_m              DOUBLE PRECISION NOT NULL,
    cep50_m             DOUBLE PRECISION NOT NULL,
    r95_m               DOUBLE PRECISION NOT NULL,

    is_significant      BOOLEAN NOT NULL,

    CONSTRAINT metrics_by_age_uniq
        UNIQUE (metrics_id, age_bin_start_s),
    CONSTRAINT metrics_by_age_bin_order
        CHECK (age_bin_end_s > age_bin_start_s),
    CONSTRAINT metrics_by_age_start_check
        CHECK (age_bin_start_s >= 0.0),
    CONSTRAINT metrics_by_age_count_check
        CHECK (epochs_count > 0)
);

COMMENT ON TABLE  metrics_by_age IS
    'Метрики точности по бинам age_of_corrections_s. '
    'is_significant=TRUE при epochs_count >= session_metrics.age_bin_min_epochs. '
    'CASCADE при удалении строки session_metrics.';
COMMENT ON COLUMN metrics_by_age.age_bin_start_s IS
    'Левая граница бина (включительно). Шаг — session_metrics.age_bin_width_s.';

-- UNIQUE по (metrics_id, age_bin_start_s) автоматически создаёт btree-индекс,
-- который покрывает WHERE metrics_id = $1 ORDER BY age_bin_start_s.
